1. (10 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.


In [17]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
np.intersect1d(a,b)

array([2, 4])

2. (10 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1 6 11
2 7 12
3 8 13
4 9 14
5 10 15


In [37]:
print('Create 1d array from 1-16:')
arr = np.arange(1,16)
print(arr)
arr1 = np.reshape(arr, (3, 5))
print('Reshape matrix to get:\n', arr1)
arr1 = arr1.T
print('Transpose matrix to get:\n', arr1)

Create 1d array from 1-16:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshape matrix to get:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Transpose matrix to get:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


3. (10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as
“flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of
values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [41]:
arr3 = arr1
print('We start with this:\n', arr3)
arr_flattened = np.ndarray.flatten(arr3.T)
# arr_flattened = np.ndarray.ravel(arr3.T)
print('Use flatten method from numpy ndarray on transpose to get:\n', arr_flattened)

We start with this:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
Use flatten method from numpy ndarray on transpose to get:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4. (15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column
becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and
the third column becomes the third dimension of the 3-D array.


In [46]:
arr = np.arange(1,16)
print(arr)
arr1 = np.reshape(arr, (3, 5))
# print('Reshape matrix to get:\n', arr1)
# arr1
a3_0 = np.stack((arr1[0], arr1[1], arr1[2] ), axis=1)
for item in a3_0:
    print(item)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]
[ 5 10 15]


5. ...

6. (10 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.


In [54]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
a = np.setdiff1d(a, np.intersect1d(a, b))
print('A - (A intersect B):\n', a)

A - (A intersect B):
 [ 1  7  8 15]
